### ISSUE TITLE
Preserving ordering of messages

### ISSUE THREAD

**Issue by keathley** [sevenmind/kaufmann_ex#16]
I may be incorrect here, but based on what I'm seeing looking through your library you aren't currently preserving the order of messages. By spawning a process per event you're giving up serial processing per partition which means giving up a feature of kafka that many people rely on. This might be fine for your use case and a deliberate tradeoff for performance reasons. But its probably worth making this explicit in the README since its currently stated implicitly.

**Comment by gerbal** [comment]
You are correct. The default behavior is optimized towards throughput at the expense of event ordering. 

I've added some information about this to the Readme. It should be possible to preserve message order by configuring `kaufmann_ex: max_demand: 1` in `config.exs`.

**Comment by keathley** [comment]
That makes sense and I understand why you've made the trade-off you have. But I can't help but wonder if it wouldn't make more sense to spawn a consumer per partition and then shard work across those consumers based on the partition key. That way you can increase your throughput by increasing the partitions for your topic without giving up ordering. Giving up ordering for the sake of performance is a tough choice when scaling based on partitions is already a well tested pattern in Kafka. Obviously its y'alls library and built for your use case so you have to do whats right for you 👍. I'll go ahead and close this now since there's nothing really actionable to do here.

**Comment by gerbal** [comment]
Good points, we've probably prematurely optimized for throughput. 

I've been reviewing the code, and we should be spawning a GenStage per-partition. That had been our original intent, but it was lost in development. I've opened issue #18 and will be resolving this later this week.
